services:
  play-django:
    container_name: play-django
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    stdin_open: true
    tty: true

  play-db:
    image: postgres:15.3
    container_name: play-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5436:5432"

volumes:
  postgres_data: { }
