# Generated by Django 5.1 on 2024-08-15 10:25

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = (("app", "0001_initial"),)

    operations = (
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("published_at", models.DateTimeField()),
            ],
            options={
                "db_table": "stories",
            },
        ),
    )
