# Generated by Django 5.1 on 2024-08-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='classification',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='publication',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='type',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
