# Generated by Django 5.1.1 on 2024-09-13 17:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_story_author_story_classification_story_publication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_name', models.CharField(max_length=255, unique=True)),
                ('prompt_attributes', models.JSONField()),
                ('stories', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'prompt_results',
            },
        ),
    ]
