name: Pipeline

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-22.04
    container: python:3.12-slim

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        pip install --no-cache-dir black isort pytest pytest-django

    - name: Run Black
      run: black --check .

    - name: Run isort
      run: isort --check-only .

    - name: Run Pytest
      run: pytest